services:
  - type: web
    name: ine-price-tracker-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: STORE_BASE_URL
        value: https://demo.inelabteamdev.com
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SCRAPE_STRATEGY
        value: auto
